version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    #ports:
      #- 5000:5000